# SPDX-FileCopyrightText: 2020 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT

on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: matreshka
      - uses: reznikmm/fedora-ada-action@master
        with:
          spec: matreshka/packages/travis/matreshka.spec
      - uses: reznikmm/upload-bintray-docker-action@v2
        with:
          username: reznikmm
          repository: matreshka
          package: matreshka
          version: head-fc32
          sourcePath: x86_64/*
          override: 1
          apiKey: ${{secrets.BINTRAY_API_KEY}}
